### ISSUE TITLE
Eclipse Oxygen

### ISSUE THREAD

**Issue by YoavNordmann** [helospark/SparkBuilderGenerator#17]
Hi

I tried just today to install and use this plugin in eclipse oxygen but to no avail.
The first time I tried to install it I had the "sun.security.validator.ValidatorException: PKIX path building failed" errors.
After uninstall I tried another install and this one supposedly worked, but I do not have an icon and I do not have the extra setting in the properties.
Please advise.

**Comment by helospark** [comment]
Hi YoavNordmann,
I think you have the same issue as https://github.com/helospark/SparkBuilderGenerator/issues/16#issuecomment-312512849

**Comment by YoavNordmann** [comment]
That is not really my problem as I am running java version "1.8.0_131"

I had the errors due to a bad VPN connection I had. Once I removed the VPN I uninstalled and reinstalled successfully.

Now I have the following data in my files: 
C:\Users\YoavNo\.p2\pool\features\com.helospark.SparkBuilderGeneratorFeature_0.0.10.201704081131
C:\Users\YoavNo\.p2\pool\plugins\com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar

the jar archive is opening up without a problem...
Everything seems in order except that there is nothing in preferences and i can't use the plugin...

**Comment by helospark** [comment]
Is the plugin visible under
help -> Installation details 
as installed software?

If you add error log (window -> show view -> error log) can you see anything related to the plugin?

**Comment by YoavNordmann** [comment]
1. I do see the entry in the installation details
2. There is something querious in the error log:

java.io.FileNotFoundException: C:\Program Files\eclipse\jee-oxygen\eclipse\configuration\org.eclipse.update\platform.xml (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.eclipse.equinox.internal.p2.update.ConfigurationWriter.save(ConfigurationWriter.java:34)
	at org.eclipse.equinox.internal.p2.update.ConfigurationIO.write(ConfigurationIO.java:69)
	at org.eclipse.equinox.internal.p2.update.Configuration.save(Configuration.java:46)
	at org.eclipse.equinox.internal.p2.touchpoint.eclipse.PlatformConfigurationWrapper.save(PlatformConfigurationWrapper.java:297)
	at org.eclipse.equinox.internal.p2.touchpoint.eclipse.EclipseTouchpoint.savePlatformConfigurationWrapper(EclipseTouchpoint.java:78)
	at org.eclipse.equinox.internal.p2.touchpoint.eclipse.EclipseTouchpoint.commit(EclipseTouchpoint.java:144)
	at org.eclipse.equinox.internal.p2.engine.EngineSession.commit(EngineSession.java:123)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:45)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:175)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:79)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56) 

I am running on a Windows machine sadly and this might be something no ?

**Comment by YoavNordmann** [comment]
yeah so when I ran eclipse as administrator and uninstalled and reinstalled the plugin it started to work.
Gotta Love Windows...

Thank man, You are awesome !

**Comment by helospark** [comment]
Based on the error, seems to be a permission problem.

I have encountered a similar issue with plugin install, when Eclipse is installed under program files, since in Windows, programs files can only be written by administrators.
When I have installed Eclipse, it asked to install as administrator, but when I have run it later as a regular user I seem to be able to install plugins, but after restart I was not able to see the install.
This was solved by either running as administrator (probably not advised for security reasons), or installing it to a non privileged location.

**Comment by helospark** [comment]
I'm glad it worked!

Seems to be a common issue with Eclipse, found many bugs with similar problems, for example:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=321239

Based on the tickets, it has been closed, but the issue still remains for administrator installs.
