### ISSUE TITLE
This error should not have happened!

### ISSUE THREAD

**Issue by jaredpowell** [helospark/SparkBuilderGenerator#52]
Seeing this error whenever I run the builder. This was working a few days ago. 

SpringToolSuite
eclipse.buildId=4.5.1.202001211336-RELEASE
java.version=1.8.0_231

`java.lang.IllegalArgumentException: Invalid identifier : ><
	at org.eclipse.jdt.core.dom.SimpleName.setIdentifier(SimpleName.java:243)
	at org.eclipse.jdt.core.dom.AST.newSimpleName(AST.java:2597)
	at com.helospark.spark.builder.handlers.codegenerator.component.fragment.buildermethod.StaticBuilderMethodSignatureGeneratorFragment.create(StaticBuilderMethodSignatureGeneratorFragment.java:30)
	at com.helospark.spark.builder.handlers.codegenerator.component.fragment.buildermethod.empty.BuilderMethodDefinitionCreatorFragment.createBuilderMethod(BuilderMethodDefinitionCreatorFragment.java:42)
	at com.helospark.spark.builder.handlers.codegenerator.component.RegularBuilderBuilderMethodCreator.addBuilderMethod(RegularBuilderBuilderMethodCreator.java:45)
	at com.helospark.spark.builder.handlers.codegenerator.component.RegularBuilderBuilderMethodCreator.addBuilderMethodToCompilationUnit(RegularBuilderBuilderMethodCreator.java:35)
	at com.helospark.spark.builder.handlers.codegenerator.RegularBuilderCompilationUnitGenerator.generateBuilder(RegularBuilderCompilationUnitGenerator.java:61)
	at com.helospark.spark.builder.handlers.codegenerator.RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.lambda$0(RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.java:37)
`

**Comment by helospark** [comment]
Hi Jared,

What value do you have in the following setting?
`Preferences->Java->Spark Builder generator->Create builder method templated pattern`?

The error messages seems to indicate that there are > and < symbols as the methodname.

**Comment by jaredpowell** [comment]
that field is empty. 
<img width="677" alt="Screen Shot 2020-02-04 at 7 36 34 AM" src="https://user-images.githubusercontent.com/54450933/73745499-29437100-4721-11ea-9535-b29ab712fefa.png">

**Comment by helospark** [comment]
Filling in the config with "builder" should solve this issue.
Though better validation of the configs set should be done at one point.

**Comment by jaredpowell** [comment]
that did the trick.  thank you so much!  this is an amazing plugin.
